HandyImage.user.js
Long time no see.
I missed you. I was pretty impressed that you have updated so far.
I am going to high school and I felt that I didn't know any of Javascript.
so I am learning now.
I will take a look at your script everyday and help you keep this script alive. Thanks. 
My email address: annlabv3[at]gmail[dot]com
=> Long time no see.

HandyImage.user.js
Previously I edit your code and do a pull request but I think I made some mistakes. I'm new to github :( so I did it again. Please merge the changes I made to your source.
=> Added new match pattern for "imgshots.com" site

HandyImage.user.js
Sample link: http://thumbnailus.com/img-55cf103ddfcdb.html
Actually, they changed their system: MultiHoster -> Imgshot image hosting script 
(http://codecanyon.net/item/imgshot-image-hosting-script/2558257)
=> Fix for thumbnailus.com

HandyImage.user.js
https://greasyfork.org/en/forum/discussion/5713/x
https://greasyfork.org/en/forum/discussion/5714/x
=> Add support for imgdrive.co, imgboom.net

HandyImage.user.js
https://greasyfork.org/en/forum/discussion/5726/x
=> Add support for img24.org

HandyImage.user.js
Add support for project-photo.net, img-planet.com, and greasyimage.com
=> 2015.08.19

HandyImage.user.js
https://greasyfork.org/en/forum/discussion/5839
=> Add: photolot.org

HandyImage.user.js
Added support for shareimgs.com
Discussion: https://sleazyfork.org/en/forum/discussion/5906/x
=> shareimgs.com

HandyImage.user.js
https://sleazyfork.org/en/forum/discussion/6256/x
https://sleazyfork.org/en/forum/discussion/6217/x
https://sleazyfork.org/en/forum/discussion/6280/x
=> [2015.09.29]

HandyImage.user.js
https://sleazyfork.org/en/forum/discussion/6354/x
=> [2015.10.01]

HandyImage.user.js
added support for imgtornado.com
=> [2015.10.04]

HandyImage.user.js
Solved: https://sleazyfork.org/en/forum/discussion/6429/x
=> [2015.10.11]

HandyImage.user.js
=> [2015.10.12]

HandyImage.user.js
https://sleazyfork.org/en/forum/discussion/6444/x
https://sleazyfork.org/en/forum/discussion/6516/x
=> [2015.10.13]

HandyImage.user.js
=> [2015.10.25]

HandyImage.user.js
http://imgbb.net/v-56f77e7b959d1_gangsta_blobo.gif
Currently stays stuck on "Continue to image" due to disabled button, this should fix the problem.
Normally it shouldn't affect other websites from the same case block, if anything it would prevent it from happening to those too.
=> Fix for imgbb.net

HandyImage.user.js
add hoster sximg.nl
Line 867 match-line
Line 1855 case-line
=> add hoster sximg.nl

HandyImage.user.js
tested with this link http://www.3xplanet.com/viewclkimg/170546.html
=> new host img.3xpla.net

HandyImage.user.js
sample url http://imgclick.net/063r1jylc65m
=> imgclick changed their url structure

HandyImage.user.js
link http://imagepics.xyz/img-587f658fdfaba.html
=> add imagepics.xyz

HandyImage.user.js
zupmage.eu has changed into turbopix.fr.
http://www.turbopix.fr/v/pvhlkawtdp
=> add turbopix.fr

HandyImage.user.js
- updated imgrock.net, imgview.net & imgtown.net (completely new page structure)
- slightly updated imguniversal.com & imgclick.net (workaround for adblocker input)
- added postto.me
=> updated some hosters

HandyImage.user.js
=> add imgwo.com

HandyImage.user.js
=> add imgspic.ru

HandyImage.user.js
=> add imgbun.ru

HandyImage.user.js
=> add imgleveret.com porn84.org

HandyImage.user.js
=> add moonpix.ru

HandyImage.user.js
=> add picpower.ru

HandyImage.user.js
=> add piccloud.ru

HandyImage.user.js
=> add pixxss.ru

HandyImage.user.js
=> add imgblank.com

HandyImage.user.js
=> add 2picsun.ru

HandyImage.user.js
=> add img-pika.ru

HandyImage.user.js
=> add pic2x.ru

HandyImage.user.js
=> add 1pic2x.ru

HandyImage.user.js
=> add 1pics1img.ru

HandyImage.user.js
Status Code	URL	IP	Page Type	Redirect Type	Redirect URL
302	http://picclick.ru/12/339942/	5.79.75.198	server_redirect	temporary	http://picpays.ru/12/339942/
200	http://picpays.ru/12/339942/	5.79.75.198	normal	none	none
=> picclick change picpays

HandyImage.user.js
=> add xxxwebdlxxx.org

HandyImage.user.js
pixsense.net redirect imagespicy.site
=> pixsense.net redirect imagespicy.site

HandyImage.user.js
add sizzlingclicks.com
sample 
https://www.sizzlingclicks.com/image/UFv85
=> add sizzlingclicks.com

HandyImage.user.js
=> add wwxxww.ru

HandyImage.user.js
=> add imgsky.net

HandyImage.user.js
=> add pic3you.org

HandyImage.user.js
pimpandhost moved to https so I fixed the match.
I think they also changed their page structure. I fixed the case to work, but I'm not sure if it's the best way to do it.
=> fix pimpandhost

HandyImage.user.js
Add suckmypic.net hoster, example page: http://suckmypic.net/oVQn9qHn.png
=> Add suckmypic.net

HandyImage.user.js
- https://lookimg.com/image/3.zoJRK
- https://lookimg.com/image/avengersinfinitywar2018020213564.03mqm
- https://lookimg.com/image/download-wonder-woman-hd.zICme
=> Add lookimg.com

HandyImage.user.js
https://github.com/Owyn/HandyImage/issues/321
=> Add trans.firm.in

HandyImage.user.js
This PR add support for 9 sites.
All the sites I add use existing logic.
=> Add: support for 9 sites

HandyImage.user.js
following hosts have been renamed:
imgoutlet.pw -> outletpic.com
imgview.pw -> imgviu.com
imgmaze.pw -> mazpic.com
=> fix host renamings

HandyImage.user.js
- https://www.imgbox.eu/image/1ORzO
- https://www.imgbox.eu/image/1OSrl
- https://www.imgbox.eu/image/1OvHZ
=> Add new host "imgbox.eu"

HandyImage.user.js
example: http://mrlzqoe.buzz/tfoxw
=> new domain for same website added

HandyImage.user.js
- Fixes #514
- add imgbibam.online
=> Multiple fixes

HandyImage.user.js
add support for `https://img.trafficimage.club/image/*` urls.
=> Update HandyImage.user.js for img.trafficimage.club

HandyImage.user.js
https://idol69.net/upload/r1ZIpD2xaHQ4cHi-FC2-PPV-3895608.jpg
=> add idol69[.]net

HandyImage.user.js
Removed expired/unregistered domains:
0img.ws
1pics.ru
1pics1img.ru
2pixxsee.ru
alesher.com
beautifulero.com
bulkimg.info
croftimage.com
fileaimage.com
image-server.ru
imagesaur.com
imgbew.buzz
imgbox.eu
imgbros.xyz
imgbun.ru
imgchilibum.ru
imgease.re
imgkoc.buzz
imgroute.com
imgshow.me
imgtigr.xyz
imguo.buzz
imgveni.xyz
jpgstore.ru
kuvajako.com
kuvapankki.in
linkmypic.com
moonpix.ru
myimageshare.com
mynameismiz.com
p0xpicmoney.ru
pic2x.ru
picker-click.ru
picr.ws
picshome.ru
pikczery.pl
pikoclick.ru
pixxss.ru
sexyimg.eu
thepornfeeds.com
xpic.biz
=> Removed expired/unregistered domains

HandyImage.user.js
NSFW
`https://porn4f.com/upload/hhulQF3MSDseoKT-SSIS-913.jpg`
`https://ovabee.com/upload/SXpU4RaLyFTJG0f-DASS-241.jpg`
=> add some sites

HandyImage.user.js
cnxx[.]me and cnpics[.]org
`https://cnxx.me/upload/G9mDiLjRC5dRpw8-FC2-PPV-1844229.jpg`
`https://cnpics.org/upload/b0m2wtMosyNNgya-FC2-PPV-1788615.jpg`
NSFW
=> add 2 sites

HandyImage.user.js
`https://cosplay18.pics/upload/en/3WlWEwxKDDFXQjW-FC2-PPV-4141956.jpg`
=> add cosplay18[.]pics

HandyImage.user.js
`http://imgblaze.net/6bmo8mdxl`
=> add imgjjtr.sbs

HandyImage.user.js
[NSFW] `https://4fuk.me/upload/wt1vHhCz5AHTyDw-SONE-427.jpg`
=> add 4fuk[.]me

HandyImage.user.js
NSFW `https://javsunday.com/upload/en/USfWmvR9xVzqq8I-FC2-PPV-4530999_2.jpg`
=> add javsunday

HandyImage.user.js
NSFW https://hentaipig.com/upload/en/JEnZhSSmPVX85f0-RKI-692.jpg
=> Add hentaipig

HandyImage.user.js
NSFW https://hentaicovid.com/uploads/en/pihmiDtRTCjkNFt-FC2-PPV-4583444_s.jpg
=> Add hentaicovid

HandyImage.user.js
javbee.vip, fc2ppv.stream, blackwidof.org
=> add 3 sites
